config/routes.rb
Rails.application.routes.draw do
  resources :winners
  resources :computers
  resources :users do
    resources :games do
      post "/next_round", to:"games#next_round", as: "next_round"
      post "/left_hook", to: "games#left_hook", as:"left_hook"
      post "/right_hook", to: "games#right_hook", as:"right_hook"
      post "/left_dodge", to: "games#left_dodge", as:"left_dodge"
      post "/right_dodge", to: "games#right_dodge", as:"right_dodge"
      post "/uppercut", to: "games#uppercut", as:"uppercut"
    end
  end
  root "users#new"

 get "/users/:id/leaderboard", to: "winners#index", as:"leaderboard"
 
 resources :users do
  get "/computer_lvl", to: "games#computer_lvl", as:"computer_lvl"
 end

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end

app/models/user.rb
class User < ApplicationRecord
    before_save :ap_adjust
    has_many :games
    has_many :winners


    def wins
    wins = Winner.all.select {|winner| winner.user == self}.count
    wins ||= 0
    end

    def high_score
        wins = Winner.all.select {|winner| winner.user == self}
        if wins != []
        high_score = wins.reduce(0) do |score, win|
            
            if win.user_points > score
                score = win.user_points
            end
            score
        end
        else
            high_score = 0
        end
        high_score
    end

    private

    def ap_adjust
        if ap < 10
            self.ap = 10
        elsif ap > 35
            self.ap = 35
        end
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
    @user = User.new
    @game = Game.new

    end

    def create 
        @user = User.find_or_create_by(params.require(:user).permit(:name))
        redirect_to @user
      
    end

    def show 
        @user = User.find(params[:id])
     

    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="ring home">
<h1>Flatiron Punch-Out</h1>

<h2>Oh no! Your instructors just deployed 30 labs!!<br>
        Someone needs to stop them!!<br></h2>

        <%= form_for @user do |f| %>
        <%= f.text_field :name, :placeholder => "Name" %><br>
        <%= f.submit "Submit" %>
        <% end %>

 <p style= "color: rgb(0, 255, 0)">Game Rules:</p>



    <p> You and Computer start with 100 health points.</p>
<p> Use right hook and left hook to attack.</p>
<p>Use left dodge and right dodge to parry.</p>
<p>Successful attacks do 10 damage.</p>
<p>Successful dodges increases your attack power by 5.</p>
<p>3 successful hits gives you a special move that gives 20 damage.</p>
<p>Best out of three round wins!</p>
<p>Defeat all your opponents and then come face to face with the legendary...</p>
<span style="color: rgb(255, 0, 0)">Red Darkness!</span> <br><br>


</div> <br>

app/views/users/show.html.erb
<div class="ring user"> Hello, <%= @user.name %>
    <p> You have defeated <%= @user.wins %> opponents.</p>
    <%= button_to "Play Game", user_computer_lvl_path(@user), method: :get%>
    <%= button_to "Leaderboard", leaderboard_path(@user), method: :get%>
    <%= button_to "Logout", new_user_path, method: :get%>
</div>