config/routes.rb
Rails.application.routes.draw do
  resources :winners
  resources :computers
  resources :users do
    resources :games do
      post "/next_round", to:"games#next_round", as: "next_round"
      post "/left_hook", to: "games#left_hook", as:"left_hook"
      post "/right_hook", to: "games#right_hook", as:"right_hook"
      post "/left_dodge", to: "games#left_dodge", as:"left_dodge"
      post "/right_dodge", to: "games#right_dodge", as:"right_dodge"
      post "/uppercut", to: "games#uppercut", as:"uppercut"
    end
  end
  root "users#new"

 get "/users/:id/leaderboard", to: "winners#index", as:"leaderboard"
 
 resources :users do
  get "/computer_lvl", to: "games#computer_lvl", as:"computer_lvl"
 end

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
    belongs_to :computer
    
    def fight_lh
        computer = self.computer.moves
        
        if computer == "lh"
            self.computer.hp -= self.user.ap 
            self.user.hp -= self.computer.ap
            self.computer.save
            self.user_hits += 1
            self.user.points += self.user.ap
            self.save
            self.user.save
            computer = "You Both Trade Left Hooks"
        elsif computer == "rh"
            self.user.ap = self.user.ap - 5
            self.user.save
            computer = " #{self.computer.name} Blocks!"
        elsif computer == "ld"
            computer = "Your Left Hook Misses!"
        elsif computer == "rd"
            self.computer.hp -= self.user.ap 
            self.computer.save
            self.user.points += self.user.ap
            self.user_hits += 1
            self.user.save
            self.save
            computer = "You Land a Left Hook!"
        end
        computer
    end

        def fight_rh
            computer = self.computer.moves
        
            if computer == "lh"
                self.user.ap =  self.user.ap - 5
                self.user.save
                computer = " #{self.computer.name} Blocks!"

            elsif computer == "rh"
                self.computer.hp -= self.user.ap 
                self.user.hp -= self.computer.ap
                self.user.points += self.user.ap
                self.user.save
                self.computer.save
                self.user_hits += 1
                self.save
                computer = "You Both trade Right Hooks"
            elsif computer == "ld"
                self.computer.hp -= self.user.ap 
                self.computer.save
                self.user_hits += 1
                self.user.points += self.user.ap
                self.user.save
                self.save
                computer = "Your Right Hook Lands"
            elsif computer == "rd"
                computer = "Your Right Hook Misses!"
               
            end
    
            computer
        end

        def fight_rd
            computer = self.computer.moves
        
            if computer == "lh"
                self.user.hp -= self.computer.ap
                self.user.save
                computer = "#{self.computer.name} Connects with a Left Hook!"
            elsif computer == "rh"
                self.user.ap = self.user.ap + 5
                self.user.points += 10
                self.user.save
                self.save
                computer = "You Dodge #{self.computer.name}'s Right Hook!"
            elsif computer == "ld"
                self.user.ap = self.user.ap + 5
                self.user.points += 10
                self.user.save
                computer = "You Both Dodge"
            elsif computer == "rd"
                self.user.ap = self.user.ap + 5
                self.user.save
                self.user.points += 10
                self.user.save
                computer = "You Both Dodge"

            end
            computer
    
        end

        def fight_ld
            computer = self.computer.moves
        
            if computer == "lh"
                self.user.ap = self.user.ap + 5
                self.user.points += 10
                self.user.save
                computer = "You Dodge #{self.computer.name}'s Left Hook"
            elsif computer == "rh"
                self.user.hp -= self.computer.ap
                self.user.save
                computer = "#{self.computer.name} Connects with a Right Hook!"
            elsif computer == "ld"
                self.user.ap = self.user.ap + 5
                self.user.points += 10
                self.user.save
                computer = "You Both Dodge"
            elsif computer == "rd"
                self.user.ap = self.user.ap + 5
                self.user.points += 10
                self.user.save
                computer = "You Both Dodge"
            end
            computer
    
        end

        def uppercut
            self.computer.hp -= 20
            self.computer.save
            self.user.points += 20
            self.user.save
            
        end
    




end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def new
    end

    def create
    @user = User.find(params[:user_id])
    if @user.level == 2
        flash[:computer] = ""
        @computer = Computer.create(name: "Sebastian", ap: 20)
        @game = Game.create(user_id: @user.id, computer: @computer)
        redirect_to "/users/#{@user.id}/games/#{@game.id}"
    elsif @user.level == 3
        flash[:computer] = ""
        @computer = Computer.create(name: "Red Darkness", ap: 30)
        @game = Game.create(user_id: @user.id, computer: @computer)
        redirect_to "/users/#{@user.id}/games/#{@game.id}"
    else 
        flash[:computer] = ""
        @user.points = 0
        @user.level = 1
        @computer = Computer.create(name: "Yoan")
        @game = Game.create(user_id: @user.id, computer: @computer)
        @user.save
        redirect_to "/users/#{@user.id}/games/#{@game.id}"
    end


    end

    def show
        @user = User.find(params[:user_id])
        @game = Game.find(params[:id])
        @computer = @game.computer
        if @game.computer.hp <= 0 && @game.round <= 3 && @game.user_wins < 2 && @game.computer_wins < 2
            flash[:results] = "You Win!"
            @game.points += @user.hp + @user.ap
            @game.round += 1
            @game.user_wins += 1
            @game.user_hits = 0
            @user.hp = 100
            @user.ap = 10
            @user.save
            @computer.hp = 100
            @user.save
            @computer.save
            @game.save
            render :round unless @game.computer_wins >= 2 || @game.user_wins >= 2
        elsif @user.hp <= 0 && @game.round <= 3 && @game.user_wins < 2 && @game.computer_wins < 2
            flash[:results] = "You lose!"
            @user.points -= 50
            @game.round += 
            @game.computer_wins += 1
            @user.hp = 100
            @game.user_hits = 0
            @user.ap = 10
            @user.save
            @computer.hp = 100
            @computer.save
            @game.save
            render :round unless @game.computer_wins >= 2 || @game.user_wins >= 2
        end
        if @game.computer_wins >= 2
            @user.level = 1
            @user.points = 0
            @user.save
            render :lose
        elsif @game.user_wins >= 2
            winner = Winner.create(user: @user, game_id: @game.id, user_points: @user.points)
            @game.user_wins += 1
            @game.user_hits = 0
            @user.hp = 100
            @user.ap = 10
            @user.save
            @computer.hp = 100
            @user.save
            @computer.save
            @game.save
            @user.level += 1
            @user.save
            render :win
        end

    end

    def left_hook
        @game = Game.find(params[:game_id])
        computer = @game.fight_lh
        flash[:computer] = computer
        redirect_to user_game_path(params[:user_id],@game)
    end

    def right_hook
        @game = Game.find(params[:game_id])
        computer = @game.fight_rh
        flash[:computer] = computer
        redirect_to user_game_path(params[:user_id],@game)
    end
    def left_dodge
        @game = Game.find(params[:game_id])
        computer = @game.fight_ld
        flash[:computer] = computer
        redirect_to user_game_path(params[:user_id],@game)
    end
    def right_dodge
        @game = Game.find(params[:game_id])
        computer = @game.fight_rd
        flash[:computer] = computer
        redirect_to user_game_path(params[:user_id],@game)
    end

    def uppercut
        @game = Game.find(params[:game_id])
        @game.uppercut
        @game.user_hits = 0
        @game.save
        redirect_to user_game_path(params[:user_id],@game)
        flash[:computer] = "Uppercut!! 20 Damage!"
    end

    def computer_lvl
        @user = User.find(params[:user_id])
        render :computer_lvl
    end

    def next_round
        @game = Game.find(params[:game_id])
        redirect_to user_game_path(params[:user_id],@game)
    end
   
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/computer_lvl.html.erb
<div class="ring">
    <% if @user.level == 2%>
    <img src="https://i.ibb.co/mB0rd6T/SEBVSPAGE-4x.png">
    <% elsif @user.level == 3%>
    <img src="https://i.ibb.co/3pFXDdf/REDDVSPAGE-4x.png">
    <% else%>
    <img src="https://i.ibb.co/kg2H89d/YOANVSPAGE-4x.png">
    <% end %>
    <div class="fight">
    <%= link_to  image_tag("https://i.ibb.co/0jKvqdM/fight-button-4x.png") , user_games_path(@user), method: :post%></div>
</div>

app/views/games/lose.html.erb
<div class="lose">
<%= button_to "My Page", @user, method: :get %> </div>
<%= audio_tag "lose.mp3", id:"sound", class: "audio-to-play", autoplay: true %>

app/views/games/menu.html.erb
<%= button_to "Leaderboard", leaderboard_path(1), method: :get %>
<%= button_to "1 Player Fight", one_player, method: :get %>
<%= button_to "2 Player Fight", two_player, method: :get %>

app/views/games/round.html.erb
<div class="ring">
   <% if @game.round == 2%>
    <img src="https://i.ibb.co/yPkxSBz/Asset-5-4x.png">
    <%= audio_tag "round.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
    
    <% elsif @game.round == 3 %>
    <img src="https://i.ibb.co/S0NkP27/round-3-4x.png">
    <%= audio_tag "round.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
   <% end %>
    <%= button_to "Continue", user_game_next_round_path(@user, @game)%>
</div>

app/views/games/show.html.erb
    <div class="ring">
        <div class="points">
            Points: <%= @user.points%>
        </div>
        <div class="round">
                Round: <%= @game.round %>
        </div>
        <% if flash[:computer] && @user.level == 1 %>
            
        <% if flash[:computer].include?("Your Right Hook Lands")%> 
                <img src="https://i.ibb.co/QC2rdMg/LVL1-USERRIGHTHOOKHIT-4x.png">   
                <%= audio_tag "landed_punch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>         
        
                <%elsif flash[:computer].include?("You Land a Left Hook")%> 
                <img src="https://i.ibb.co/py5Ms7y/LVL1-USERLEFTHOOKHIT-4x.png">
                <%= audio_tag "landed_punch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>   
        
                <%elsif flash[:computer].include?("Your Left Hook Misses")%> 
                <img src="https://i.ibb.co/dpbhp9f/LVL1-LEFTHOOKMISS-4x.png">
                <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %> 
        
                <%elsif flash[:computer].include?("Your Right Hook Misses")%> 
                <img src="https://i.ibb.co/kS9PNtn/LVL1-RIGHTHOOKMISS-4x.png">
                <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
                <%elsif flash[:computer].include?("You Dodge Yoan's Left Hook")%> 
                <img src="https://i.ibb.co/nB18Q98/LVL1-YOANLEFTHOOKDODGE-4x.png" >
                <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
                <%elsif flash[:computer].include?("You Dodge Yoan's Right Hook")%> 
                <img src="https://i.ibb.co/NC1v3MT/LVL1-YOANRIGHTHOOKDODGE-4x.png">
                <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
            
                <%elsif flash[:computer].include?("Yoan Connects with a Right Hook!")%>
            <%= audio_tag "oppHit.mp3", id:"sound", class: "audio-to-play", autoplay: true %>     
                <img src="https://i.ibb.co/84CvqpG/LVL1-YOANRIGHTHOOKHIT-4x.png">
            
                <%elsif flash[:computer].include?("Yoan Connects with a Left Hook!")%> 
            <%= audio_tag "oppHit.mp3", id:"sound", class: "audio-to-play", autoplay: true %>  
                <img src="https://i.ibb.co/f2XGnmj/LVL1-YOANLEFTHOOKHIT-4x.png">
            
                <%elsif flash[:computer].include?("Uppercut!!")%> 
                <img src="https://i.ibb.co/W2Jb4xL/LVL1-UPPERCUT-4x.png">
                <%= audio_tag "uppercut.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
                
                <% elsif flash[:computer].include?("Yoan Blocks")%>
                <%= audio_tag "block.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
                <img src="https://i.ibb.co/f4x5z5b/LVL1-BLOCK-4x.png">
                
                <% elsif flash[:computer].include?("Right Hooks") %>
                <img src="https://i.ibb.co/yYTRRsN/LVL1-bothpunch-RIGHTHOOK-4x.png">
                <%= audio_tag "bothpunch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
                
                <% elsif flash[:computer].include?("Left Hooks") %>
                <img src="https://i.ibb.co/KKQtFvK/LVL1-bothpunchLEFTHOOK-4x.png">
                <%= audio_tag "bothpunch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>


            <%else%>
        
            <img
             src="https://i.ibb.co/jLcg9N0/LVL1-STANDOFF-4x.png">
                <% end%>
            <%elsif @user.level == 1%>
        


            <img src="https://i.ibb.co/jLcg9N0/LVL1-STANDOFF-4x.png">
        <% end%>




            <!-- ---------------------------------------------------------------- -->
            <% if flash[:computer] && @user.level == 2 %>
        

            <%if flash[:computer].include?("Your Right Hook Lands")%> 
            <img src="https://i.ibb.co/CMYDncX/LVL2-USERRIGHTHOOKHIT-4x.png"> 
            <%= audio_tag "landed_punch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>      
        
            <%elsif flash[:computer].include?("You Land a Left Hook")%> 
            <img src="https://i.ibb.co/qxk700Y/LVL2-USERLEFTHOOKHIT-4x.png">
            <%= audio_tag "landed_punch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>   
        
            <%elsif flash[:computer].include?("Your Left Hook Misses!")%> 
            <img src="https://i.ibb.co/r5YgnHD/LVL2-USERLEFTHOOKMISS-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
            <%elsif flash[:computer].include?("Your Right Hook Misses")%> 
            <img src="https://i.ibb.co/MCwCT77/LVL2-USERRIGHTHOOKMISS-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
            <%elsif flash[:computer].include?("You Dodge Sebastian's Left Hook")%> 
            <img src="https://i.ibb.co/Bf4CPmV/LVL2-SEBLEFTHOOKMISS-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
            <%elsif flash[:computer].include?("You Dodge Sebastian's Right Hook")%> 
            <img src="https://i.ibb.co/tBJvDZM/LVL2-SEBRIGHTHOOKMISS-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
            <%elsif flash[:computer].include?("Sebastian Connects with a Right Hook!")%> 
            <img src="https://i.ibb.co/vLtxJWV/LVL2-SEBRIGHTHOOKHIT-4x.png">
            <%= audio_tag "oppHit.mp3", id:"sound", class: "audio-to-play", autoplay: true %>  
    
            <%elsif flash[:computer].include?("Sebastian Connects with a Left Hook!")%> 
        <%= audio_tag "oppHit.mp3", id:"sound", class: "audio-to-play", autoplay: true %>  
            <img src="https://i.ibb.co/V99Jg77/LVL2-SEBLEFTHOOKHIT-4x-png-4x.png">
    

            <%elsif flash[:computer].include?("Uppercut!!")%> 
            <img src="https://i.ibb.co/NFQJBzj/LVL2-UPPERCUT-4x.png">
            <%= audio_tag "uppercut.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
    

            <%elsif flash[:computer].include?("Sebastian Blocks")%>
            <%= audio_tag "block.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
            <img src="https://i.ibb.co/KzDg8tF/LVL2-BLOCK-4x.png">
    

            <% elsif flash[:computer].include?("Right Hooks") %>
            <img src="https://i.ibb.co/9tWh23r/LVL2-bothpunchRIGHHOOK-4x.png">
            <%= audio_tag "bothpunch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
            
            <% elsif flash[:computer].include?("Left Hooks") %>
            <img src="https://i.ibb.co/JFGsXdp/LVL2-bothpunchLEFTHOOK-4x.png">
            <%= audio_tag "bothpunch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>

            
            <%else %>
            
            <img src="https://i.ibb.co/Yc88bWp/LVL2-STANDOFF-4x.png">
    

            <%end%>
        <%elsif @user.level == 2%>
            
        <img src="https://i.ibb.co/Yc88bWp/LVL2-STANDOFF-4x.png">
    

            
            <%end%>
     <!-- --
        -------------------------------------------------------------- -->
    

     <%if flash[:computer] && @user.level == 3 %>
        <%if flash[:computer].include?("Your Right Hook Lands")%> 
            <img src="https://i.ibb.co/LvBpYwg/user-throws-right-hook-4x.png">  
            <%= audio_tag "landed_punch.mp3", id:"sound", class: "audio-to-play", autoplay: true %> 
        
        <%elsif flash[:computer].include?("You Land a Left Hook")%> 
            <img src="https://i.ibb.co/qNN4ysr/user-left-hook-4x.png">
            <%= audio_tag "landed_punch.mp3", id:"sound", class: "audio-to-play", autoplay: true %> 
        
        <%elsif flash[:computer].include?("Your Left Hook Misses!")%> 
            <img src="https://i.ibb.co/L5F3hn2/LVL3-USERLEFTHOOKREDDODGE-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
        <%elsif flash[:computer].include?("Your Right Hook Misses")%> 
            <img src="https://i.ibb.co/8mXQqY3/LVL3-USERRIGHTHOOKREDDODGE-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
    
        <%elsif flash[:computer].include?("You Dodge RedDarkness's Left Hook")%> 
            <img src="https://i.ibb.co/B6DRYCp/LVL3-REDLEFTHOOKDODGE-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
    
        <%elsif flash[:computer].include?("You Dodge RedDarkness's Right Hook")%> 
            <img src="https://i.ibb.co/zJb7fgG/LVL3-REDRIGHTHOOKDODGE-4x.png">
            <%= audio_tag "miss.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
    
        <%elsif flash[:computer].include?("RedDarkness Connects with a Right Hook!")%> 
            <%= audio_tag "oppHit.mp3", id:"sound", class: "audio-to-play", autoplay: true %>  
            <img src="https://i.ibb.co/zFZxRCk/LVL3-REDRIGHTHOOKHIT-4x.png">
    
        <%elsif flash[:computer].include?("RedDarkness Connects with a Left Hook!")%> 
            <%= audio_tag "oppHit.mp3", id:"sound", class: "audio-to-play", autoplay: true %>  
            <img src="https://i.ibb.co/wzG5b6P/LVL3-REDLEFTHOOKHIT-4x.png">
    

         <%elsif flash[:computer].include?("Uppercut!!")%> 
            <img src="https://i.ibb.co/68jcY9R/LVL3-UPPERCUT-4x.png">
            <%= audio_tag "uppercut.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
    

        <%elsif flash[:computer].include?("RedDarkness Blocks") %>
            <img src="https://i.ibb.co/09yKQrw/LVL3-BLOCK-4x.png">
            <%= audio_tag "block.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        

        <% elsif flash[:computer].include?("Right Hooks") %>
            <img src="https://i.ibb.co/9qkFMpB/LVL3-bothpunch-RIGHT-HOOK-4x.png">
            <%= audio_tag "bothpunch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        
        <% elsif flash[:computer].include?("Left Hooks") %>
            <img src="https://i.ibb.co/DpZFhF9/LVL3-bothpunchLEFTHOOKS-4x.png">
            <%= audio_tag "bothpunch.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
        <%else %>
        
        <img src="https://i.ibb.co/MBthsQ1/LVL3-USER-STAND-4x.png">
    

         <%end%>
        <% elsif @user.level == 3 %>
            <img src="https://i.ibb.co/MBthsQ1/LVL3-USER-STAND-4x.png">
        <%end%>
        
        <div class= "user_hp">
            <%=@user.name%> Health: <%= @user.hp %>
        </div>
            <div class="comp_hp">
                <%=@computer.name%> Health: <%= @game.computer.hp %>
            </div>
        </div>
    

</div>
</div>
<% if @game.user_hits >= 3 %>
    <div class="uppercut">
        <%= link_to image_tag("https://i.ibb.co/NV33Ptw/uppercut-button-4x.png"), user_game_uppercut_path(@user, @game), method: :post%>
        
    </div>
<% end %>

    <div class="punches clearfix">
        <div class="l_hook">
            <img src="/left_hook.png"/>
            <%=button_to "", user_game_left_hook_path(@user, @game)%> 
        </div>
        <div class="r_hook">
            <img src="/right_hook.png"/>
            <%=button_to "", user_game_right_hook_path(@user, @game)%>
        </div>
    </div>
    <div class="dodges clearfix">
        <div class= "d_left">
            <img src="/dodge_left.png"/>
            <%=button_to "", user_game_left_dodge_path(@user, @game)%>
        </div>
        <div class= "d_right">
            <img src="/dodge_right.png"/>
            <%=button_to "", user_game_right_dodge_path(@user, @game)%>
        </div>
    
 <div class= "game_messages"> 
        <% if flash[:computer] %>
        <%= flash[:computer] %>
        <% end %> <br>
        <% if flash[:results] %>
        <%= flash[:results] %>
        <% end %>
</div>

app/views/games/win.html.erb
<div class="ring"><% if @computer.name == "Yoan" %>
<% @user.level = 2 %>
<% @user.save %>
<img src="https://i.ibb.co/7gGnKtw/KO-YOAN-4x.png">
<% elsif @computer.name == "Sebastian" %>
<% @user.level = 3 %>
<% @user.save %>
<img src="https://i.ibb.co/FYxvBBK/SEB-KO-4x.png">
<% elsif @computer.name = "Red Darkness"  %>
<% @user.level = 4 %>
<% @user.save %>
<img src="https://i.ibb.co/K9nrZPr/you-win-page-4x.png">
<%= audio_tag "Win.mp3", id:"sound", class: "audio-to-play", autoplay: true %>
    

<% end %> 


<% if @user.level <= 3 %>
<%= button_to "My Page", @user, method: :get %>
<%= button_to "Next Level", user_computer_lvl_path(@user), method: :get%>
<% else %>
<%= button_to "My Page", @user, method: :get %>
<% end %> 
</div>